#!/bin/bash
# Geogallery script, v1

echo -e "\nHello, welcome to creating your own geogallery."
echo -e "\nCreating geogallery for folder in path: $1\n"

if [ -e "$1" ]; then
    rm -rf "$1/geogallery"
    cp -rv ./app "$1/geogallery"
    mv "$1/geogallery/styles/index.scss" "$1/geogallery/styles/index.css"

    ./util/geogallery-resize-media 1000 "$1/FINAL_PHOTOS" "$1/geogallery/images"
    ./util/geogallery-resize-media 250 "$1/FINAL_THUMBNAILS" "$1/geogallery/thumbnails"
    ./util/geogallery-extract-media "$1/geogallery/images" > "$1/geogallery/media.json"
else
    echo "error"
fi