#!/bin/bash
# Geogallery script, v1

ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) # @see http://stackoverflow.com/a/246128

if [ -z "$1" ]; then
    echo "Error: Please provide a source path as first argument"
    exit 1
fi

echo -e "\nHello, welcome to creating your own geogallery."
echo -e "\nCreating geogallery for folder in path: $1\n"

cd "$1"
mkdir -p geogallery/{images,thumbnails}
cd geogallery

$ROOT/geogallery-resize-media 1000 ../FINAL_PHOTOS images
$ROOT/geogallery-resize-media 500 ../FINAL_THUMBNAILS thumbnails
$ROOT/geogallery-resize-media 1500 ../FINAL_BG_IMAGE .
$ROOT/geogallery-extract-media images > media.json
$ROOT/geogallery-extract-tracks ../FINAL_GPS > tracks.json
cp -f ../config.json .
$ROOT/geogallery-assemble . > index.html

# Clean up unnecessary files from target
rm -f {config,media,tracks}.json